print("Welcome to the programing BAND Generator\n")
city = input("What's the name of the city you grew up in\n")
print(city)
pet = input("what's your pet's name\n")
print(pet)
print(f"Your band name could be {city} {pet}")